# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-26 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BotRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=64)),
                ('run_name', models.CharField(max_length=64)),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wdid', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('action', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=255, null=True)),
                ('msg', models.CharField(max_length=255, null=True)),
                ('bot_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.BotRun')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField(blank=True, null=True)),
                ('release', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set([('name', 'release')]),
        ),
        migrations.AddField(
            model_name='log',
            name='external_id_prop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Property'),
        ),
        migrations.AddField(
            model_name='domain',
            name='properties',
            field=models.ManyToManyField(to='report.Property'),
        ),
        migrations.AddField(
            model_name='botrun',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Domain'),
        ),
        migrations.AddField(
            model_name='botrun',
            name='sources',
            field=models.ManyToManyField(to='report.Source'),
        ),
        migrations.AddField(
            model_name='bot',
            name='domain',
            field=models.ManyToManyField(to='report.Domain'),
        ),
        migrations.AddField(
            model_name='bot',
            name='maintainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='botrun',
            unique_together=set([('bot', 'run_id', 'run_name')]),
        ),
    ]
