# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-31 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskrun',
            unique_together=set([('task', 'timestamp')]),
        ),
    ]
